### ISSUE TITLE
Exposed database credentials

### ISSUE THREAD

**Issue by overlinden** [Fila2Basuras/fila2_basuras#2]
Hi,

you have a potential security breach in your code.
https://github.com/Fila2Basuras/fila2_basuras/blob/955742aed20102280428936e979bcce31e087019/src/main.py#L14
https://github.com/Fila2Basuras/fila2_basuras/blob/955742aed20102280428936e979bcce31e087019/src/libreria/conexion.py#L5
Your database credentials are exposed. It's advised to use environment variables instead.

Best regards
Oliver

**Comment by fjimenezJOB** [comment]
Thanks for the warning, we understand it's a security breach.
